# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.8'
services:
  subco-app:
    image: subco
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@subco-oracle:1521:subco
      - SPRING_LIQUIBASE_URL=jdbc:oracle:thin:@subco-oracle:1521:subco
      - JHIPSTER_CACHE_REDIS_SERVER=redis://subco-redis:6379
      - JHIPSTER_CACHE_REDIS_CLUSTER=false
      # - JHIPSTER_CACHE_REDIS_SERVER=redis://subco-redis:6379
      # - JHIPSTER_CACHE_REDIS_CLUSTER=true
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:8088:8088
  subco-redis:
    image: redis:6.2.7
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:6379:6379
